/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_update_Updater */

#ifndef _Included_update
#define _Included_update
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_update_Updater
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_suli_testupdate_Updater_bspatch
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
